[[redirects]]
  from = "/api/*"
  to = "https://api.open-meteo.com/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }


[[redirects]]
  from = "/forecast/*"
    to = "https://api.meteomatics.com/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }